name = "L1210"
uuid = "3c91580c-eb7c-4e2e-9dd5-863e15a69481"
authors = ["ethan-air <ethanlevien@gmail.com>"]
version = "0.1.0"

[deps]
AbstractGPs = "99985d1d-32ba-4be9-9821-2ec096f28918"
Alert = "28312eec-4d86-447d-83ad-bc2b262de792"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CausalityTools = "5520caf5-2dd7-5c5d-bfcb-a00e56ac49f7"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
GaussianProcesses = "891a1506-143c-57d2-908e-e1f8e92e6de9"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LineSearches = "d3d80556-e9d4-5f37-9878-2ab0fcc64255"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariateStats = "6f286f6a-111f-5878-ab1e-185364afe411"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
ParameterHandling = "2412ca09-6db7-441c-8e3a-88d5709968c5"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
SavitzkyGolay = "c4bf5708-b6a6-4fbe-bcd0-6850ed671584"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Stheno = "8188c328-b5d6-583d-959b-9690869a5511"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
